### ISSUE TITLE
정적 웹페이지 구성 및 사이트 정보 저장 API 구현

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#11]
- [ ] 정적 웹페이지 구성
- [ ] 사이트 정보 저장 API 구현 (lambda)
   - POST API(endpoint: `/api/v1/site`)

**Comment by jongwoo328** [comment]
@hyejungg 
같은 프로젝트 내에 사이트 데이터 가져오는 lambda, 데이터 저장용 lambda 두 가지에 대한 코드가 포함되어야 하는데.. 
어떻게 할지 생각해보고 있는데 프로젝트 구조를 바꾸는건 어떨까 합니다. 이런 느낌으로요..

근데 이렇게 되면 공통으로 쓰는 common 때문에 docker 이미지 빌드할 때 조금 까다로울 것 같기도 한데 어떤가요?

```
project-root/
├── common/              # 공통 코드 디렉토리
│   ├── config/          
│   ├── models/          
│   └── loader/          
└── lambdas/             # 각 Lambda 함수 디렉토리
    ├── lambdaA/         
    │   ├── src/         
    │   ├── Dockerfile   
    │   └── package.json 
    └── lambdaB/         
        ├── src/         
        ├── Dockerfile   
        └── package.json 
```

**Comment by hyejungg** [comment]
@jongwoo328 
괜찮은 듯 합니다! 그러면 interface 같은 부분은 common으로 갈지 모듈별로 각자 가질지도 고민해봐야 할 것 같은데 어떻게 생각하시나요?!
그리고 프로젝트 구조가 변경되는거는 별도 이슈에서 진행해주시면 감사하겠습니다 (_ _)

**Comment by jongwoo328** [comment]
@hyejungg 
SiteInfo 처럼 공통으로 사용되는 타입이나 인터페이스는 common/ 에 들어가게 될 것 같구요
해당하는 lambda 내에서만 사용된다면 해당 디렉토리 안에 선언하면 되지 않을까 싶네요

그리고 작업 진행 관련해서는
- 새로 추가되는 프로젝트 구조 변경 이슈는 #14 머지후에 하는 게 좋을 것 같고
- 그 전에는 일단 현재 구조에서 html파일 만들고 있다가 #14 와 프로젝트 구조변경까지 머지되면 여기서 merge해서 최종작업 후 PR 해볼게요

**Comment by hyejungg** [comment]
@jongwoo328 
헉 근데 지금 제가 작업하는 것(#5)과도 영향이 많이 있을 것 같은데요 ... ! 
혹시 그러면 현재 구조에서 html 파일 만드시고 ... 제 이슈 merge 된 후에 구조 변경 및 그 PR 에서 언급해주신 TrendService 소스코드 리팩토링? 하는 걸 같이 하면 어떨가요?!?

**Comment by jongwoo328** [comment]
@hyejungg 
넵 좋네요. 그럼 TrendService 리팩토링은 변경사항이 좀 된다싶으면 별도 이슈 추가할게요

**Comment by hyejungg** [comment]
의견 반영 감사합니다!!😎

**Comment by jongwoo328** [comment]
`verified` 같은 boolean 타입 key를 site 스키마에 하나 추가해서 등록은 자동으로 `false`로 저장되고
별도 확인이나 데이터조회 기능 구현 후 저희가 `true`로 변경하면 그 때 스크립트에서 사용하는 방식으로 하는건 어때요?

**Comment by jongwoo328** [comment]
무료 템플릿 + 사진 가져와서 이런 느낌으로 간단히 만들어봤어요

<img width="643" alt="image" src="https://github.com/hyejungg/ai-news-noti-bot/assets/28002600/21c6ac7c-4965-49f5-a327-b607604e670c">

**Comment by hyejungg** [comment]
@jongwoo328 
> verified 같은 boolean 타입 key를 site 스키마에 하나 추가해서 등록은 자동으로 false로 저장되고
별도 확인이나 데이터조회 기능 구현 후 저희가 true로 변경하면 그 때 스크립트에서 사용하는 방식으로 하는건 어때요?

좋은 생각입니다! 

keyword form (optional) 도 같이 넣어주시면 좋을 것 같아요! (필수 파라미터는 사이트명과 url)
근데 생각해보니 누가 제출했는지는 없어도 괜찮을까요 ?

**Comment by jongwoo328** [comment]
@hyejungg 
그것도 있으면 좋을 것 같네요 일단 넣어볼게요 optional로?
