### ISSUE TITLE
lambda 배포 자동화 구성

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#12]
- [ ] 빌드, 이벤트 트리거(매일 10시 카카오워크로 메시지 전송 (웹훅 이용)), 배포 자동화

 * EventBridgeEvent 관련 타입 선언 (types/aws/lambda.ts)
 * 참고: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-events-structure.html

**Comment by jongwoo328** [comment]
참고하세요
https://chat.openai.com/share/9836ddd9-90e3-4c65-95d8-79881486e60d
