### ISSUE TITLE
lambda 에서 puppeteer 크롬 접근 가능하도록 코드 수정??

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#26]
그 chrome 경로를 수정해줘야 했던 것 같은데 맞나요?

**Comment by jongwoo328** [comment]
[이 패키지](https://www.npmjs.com/package/chrome-aws-lambda) 사용하고
puppeteer 사용할 때

![image](https://github.com/hyejungg/ai-news-noti-bot/assets/28002600/38816270-8a1d-4100-bf7c-f76b4644f60c)

이렇게 사용하면 된다고 하더라고요

**Comment by hyejungg** [comment]
- real 전 테스트하는방법 정하기
  - 로컬 노트북에서 테스트(환경이 달라서 힘듬) test용 람다에서 하거나?
- [@sparticuz/chromium](https://github.com/alixaxel/chrome-aws-lambda/issues?page=2&q=is%3Aissue+is%3Aopen) 으로 바꿀 수 있는지 검토해보기
  - puppeteer-core 최신버전을 사용할 수 있으면 더 코드를 좋게 짤 수 있음

**Comment by hyejungg** [comment]
개발은 로컬에서 그냥 진행

- [ ] 개발 브랜치 생성
- [ ] 개발 환경 람다 하나 구성하고 -> feature 종합해서 람다가 잘 실행되는지를 보는 용도, real 배포 전에 확인하는 용도

- [ ] aws lambda docker 이미지로 로컬에서 쓸 수 있는지 혹은 elasticmq 같은게 잇는지 확인

**Comment by jongwoo328** [comment]
nodejs lambda 이미지
https://hub.docker.com/r/amazon/aws-lambda-nodejs

**Comment by jongwoo328** [comment]
sam으로 로컬에서 테스트하기 참고
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-invoke.html#serverless-sam-cli-using-invoke-environment-file
