### ISSUE TITLE
각 모듈 별 배포가 가능하도록 변경

### ISSUE THREAD

**Issue by jongwoo328** [hyejungg/ai-news-noti-bot#30]
- [ ] 각 모듈마다 배포 파이프라인이 독립적으로 실행되도록 구성
  - [ ] docker 사용하는 경우 Dockerfile을 각 모듈별로 생성
  - [ ] github action에서 모듈별 병렬처리 가능하도록 구성
  - [ ] merge 후 변경이 있는 모듈만 배포하도록 구성 (가능하면)

**Comment by hyejungg** [comment]
선작업으로 해야 할 것 같음
ECR 에서 벌써 프리티어 85% 썼다는 알림이 옴
![image](https://github.com/hyejungg/ai-news-noti-bot/assets/68772751/d03b9a82-9dd4-4684-ae00-a2cc28145b9f)

**Comment by jongwoo328** [comment]
https://blog.lemonbase.team/github-actions-%EB%B0%B0%ED%8F%AC-%EC%8B%9C%EA%B0%84-%EC%A4%84%EC%97%AC%EB%B3%BC%EA%B9%8C-5725b92e36d9 
참고할거있는지 보기

**Comment by hyejungg** [comment]
프로젝트 방향이 변경되어 우선 이슈를 삭제하고 추후 필요할 경우 다시 생성합니다.
