### ISSUE TITLE
키워드에 맞는 기사 추출 개선을 위한 llm 에이전트 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#45]
- [ ] 키워드 추가
    - [ ] 키워드별 llm관련 정보 뽑아오는 방식 변경하기 
       - ex. 기사 제목들을 llm에게 주고, ai 관련 뉴스만 골라달라고 한다던지..

**Comment by hyejungg** [comment]
에이전트로 만들어보면 어떨까 ?! 

### 변경되는 아키텍처
> lambda 추가
1. 파싱 agent 구성
![제목 없는 다이어그램 drawio](https://github.com/user-attachments/assets/d8b481a1-2087-4bb3-98d4-f0a3f9e3f279)

2. 파싱 agent 동작 방식
![image](https://github.com/user-attachments/assets/1cefe167-bfa7-450d-a315-9a421d1c0f13)

![image](https://github.com/user-attachments/assets/1b7e75a2-bb71-4f74-8b03-3647478ac9fa)
----
- [x] 시간 / RAM 이 감당 가능한 수준인지 확인 필요 (최대 시간이나 최대 RAM 확인)
   - 시간: 1초부터 900초(15분) 사이
   - ram: 최대 10GB
- [ ] 하나의 람다에서 돈다면 이게 효율적인가?
    - 예상 금액: 
    - [x] 나중에 사이트가 추가된다면 용량이 커질텐데 가능할지?
       - 용량은 괜찮더라도 시간이 어려울 수도 있을 듯 ... 
- [ ] CSR 하는 사이트는 agnet 가 랜더링을 할 수 있는 action 이나 도구가 있어야 할텐데 가능할지 확인 필요할 듯

-> 에어전트로 구성한다면 배포툴을 바꿔야 할 듯
-> 아니면 사내에?! 그러면 gai 모임에서 얘기해보기

**Comment by hyejungg** [comment]
@jongwoo328 다음과 같은 사유로 크롤링까지 llm에게 시키기 어려울 것 같습니다 .. 
![image](https://github.com/user-attachments/assets/2c38898f-5b80-4eb6-b0d5-e3255be6e11d)

## 확인된 내용 공유
### 1. ChatGPT 모델과 API 모델의 response 는 다르다.
> 코드에서 사용한 모델은 [여기서](https://platform.openai.com/docs/models/gpt-4o) ChatGPT 와 똑같은 모델을 사용하고 있다는 `chatgpt-4o-latest`를 사용함
- chat ui 에서 제공하는 것(일부 크롤링에 성공하여 title, url 형태의 Json 포맷으로 변경해줌)
- api 호출을 통해 응답받는 결과(나는 크롤링을 할 수 없다.)
-> 두 내용이 달라서 구글링 해보니 다음과 같은 글을 확인함
[openai 커뮤니티 글 1](https://community.openai.com/t/does-the-openai-api-provide-internet-access-for-web-browsing/696799)
[openai 커뮤니티 글2](https://community.openai.com/t/searching-internet-page-with-api-4-0/726493/1)

api를 채팅(generate)통해 크롤링을 기대하기는 어려울 것 같음.
혹시나 해서 Claude 도 확인해보았는데 채팅(generate)로는 크롤링을 기대하기는 어려울 것 같음

### 2. chat ui 에서 제공해주는 response 의 결과도 100% 신뢰할 순 없음.
[ChatGPT 에서 테스트용으로 확인해본 것](https://chatgpt.com/share/670b4a55-4ccc-8002-9b23-07c37043a734)

위 링크는 저번에 캔틴에서 같이 확인해본 내용인데 response 중에서 일부는 존재하지 않는 url이거나 url과 제목이 매칭이 실패함
그냥 문맥에 맞춰 글자를 생성한 것 같음 ... 
뭔가 후처리(해당 링크에 접속해서 존재하는 페이지인지 확인한다거나 ...)를 하면 개선해볼 수 있겠지만 1. 과 같이 api 에서 웹 검색이 불가하여 의미가 없을 것으로 보임 ...

## 진행 방향 변경
목요일에 캔틴에서 회의 했을 때 크롤링까지 성공하면 python으로 4가지 일(크롤링 + 필터링 + 중복 메시지 제거 + 메시지 전송) 을 수행하도록 변경하기로 했었는데 어려울 것 같습니다 ... 

그래서 아래와 같이 진행해야 할 것 같은데 더 좋은 방법이 있을까요? ㅠ ㅠ ㅠ ㅠ ㅠ

- **기존 news-scrapper) 크롤링, 중복 메시지 제거 + 메시지 전송**
- **에이전트) 키워드 기반 필터링**

**Comment by jongwoo328** [comment]
흐음.. 아쉽네요 
결국 페이지별 코드가 추가도긴 해야할 것 같습니다
혹시 진행하셨던 코드는 저도 실행해보려면 feat45 브랜치 보면될까요?

**Comment by hyejungg** [comment]
넵 맞습니다! 그 news-scrapper-agent 모듈에 .env 는 추가하셔야 할텐데요.
저는 이렇게 구성했습니다. 
```
# LANGSMITH 로깅 관련
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY={우선 제껄로 했어요...}
LANGCHAIN_PROJECT={우선 제껄로 했어요...}

# LANGFUSE 로깅 관련
// 사용되긴하나 langfuse 는 사내망에 있는 걸 연결한거라 요청 자체가 가지 않을 것 같아서 생략

# LLM 관련
OPENAI_API_KEY={openai key}

CRAWLING_AGENT_PROMPT_EN="<Roles and objectives>
Please find the information you want on the site based on the information below

<Context>
The site information is as follows.
- Site name: {site_name}
- Site link: {site_url}
- More info: {site_additional_info}

<Instructions>
1. Make sure to extract information from the site that is delivered.
2. If additional information is available, use the additional information to extract the article title and website link.
3. The extracted information should not be changed arbitrarily.
4. The answer must be in JSON array form, responding to the article title and the article's website link in key-value form as follows.
5. If the article information has not been imported, respond in the form of an empty array: ex. '[]'
6. Be sure to follow the instructions above."
FILTERING_AGENT_PROMPT_EN="<Roles and objectives>
From the given information, 'title' extracts only the elements related to 'LLM', 'General AI', and 'AI' from the value of the 'content' key. Please make your own judgment and extract the elements related to 'generative ai' from each object element.

<Context>
{extract_site_info}

<Instructions>
1. You must not change the content arbitrarily.
2. The answer must be in JSON array form, responding to the article title and the article's website link in key-value form as follows.
3. If there is no related element, please return an empty array. ex. '[]'
4. Be sure to follow the instructions above."

CRAWLING_AGENT_PROMPT_KO="<역할 및 목표>
아래 정보를 바탕으로 사이트에서 원하는 정보를 찾아주세요

<문맥>
사이트 정보는 다음과 같습니다.
- 사이트 이름: {site_name}
- 사이트 링크: {site_url}
- 추가 정보: {site_additional_info}

<지시문>
1. 반드시 전달되는 사이트 내에서 정보를 추출합니다.
2. 추가 정보가 있는 경우 추가 정보를 활용하여 기사 제목과 웹사이트 링크를 추출합니다.
3. 추출한 정보를 임의로 변경해선 안됩니다.
4. 답변은 반드시 JSON 배열 형태로 기사 제목(title)과 기사의 웹사이트 링크(url)를 다음과 같은 key-value 형태로 응답합니다.
5. 기사 정보를 못가져 온 경우 다음과 같이 빈 배열 형태로 응답합니다. ex. '[]'
6. 반드시 위 지침을 따르세요."
FILTERING_AGENT_PROMPT_KO="<역할 및 목표>
주어진 정보 중 'content' key의 value 중 'title'이 'LLM', 'Generative AI', 'AI'와 관련된 요소만 추출합니다. 본인이 판단하여 각 객체 요소 중 title이 generative ai 와 관련된 것을 추출해주세요.

<문맥>
{extract_site_info}

<지시문>
1. 임의로 내용을 변경해선 안됩니다.
2. 답변은 반드시 JSON 배열 형태로 기사 제목(title)과 기사의 웹사이트 링크(url)를 다음과 같은 key-value 형태로 응답합니다.  ex. '[{'title': 'Building an internal AI tool with Streamlit','url': 'https://news.hada.io/topic?id=17118'},{'title': 'Apple Depth Pro Revealed: AI Model Redefined the Rules of 3D Vision','url': 'https://news.hada.io/topic?id=17110'}]'
3. 관련 요소가 없는 경우 빈 배열을 반환해주세요. ex.'[]'
4. 반드시 위 지침을 따르세요."

```
------

아니면 news-scrapper 의 크롤링 하는 부분을 api 로 만들어서 해볼 수도 있을 것 같긴 합니다. 
이런 식으로요 .... 
1. EventBridge 가 에이전트 람다 실행 (python 코드)
2. python 코드에서 크롤링 에이전트가 function calling 으로 기존의 news-scrapper 로 크롤링을 해오고 결과를 받아옴
3. 그 결과를 바탕으로 python 코드에서 필터링 에이전트가 필터링 수행 ... 
4. python 코드에서 중복 메시지 제거 + 메시지 전송 .... 
-> 이렇게 되면 python 코드에서 몽고디비 접속, news-scrapper 를 api 형태로 변경 등등 수정 사항이 많아지긴 할 것 같네요 ..

**Comment by jongwoo328** [comment]
오 저도 그방법 생각했었는데요
지금방식보다는 그게 에이전트 쓰기엔 맞는 방식같아요
api를 람다로 한다면 easy 일것같고..
수정보단 새로만드는게 더 간단할것 같아요

**Comment by hyejungg** [comment]
그러면 저희 그 모노 레포 구성한 것도 의미가 없어지는 ... 보내줘야 하는 ... 그런데 ... 괜찮을까요 ... ? 
![image](https://github.com/user-attachments/assets/2c38898f-5b80-4eb6-b0d5-e3255be6e11d)
저도 수정보다는 아예 새로 다시 만드는게 더 빠를 것 같긴 합니다.. 
그러면 다시 역할 분담부터 해야할 일 리스트 정리도 다시 하는게 좋을 듯 해보이는데 어떻게 생각하시나요 .. ?!  
오늘 중으로 각자 생각해보고 월요일에 다시 얘기해봐도 좋을 듯 합니다.

1. 새로 만들어버리기
2. 수정해서 만들어버리기
3. 현재 구성 내에서 어떻게 해보기
4. api 로 크롤링이 가능하도록 더 연구해보기 (?)

**Comment by jongwoo328** [comment]
네 그럼 직접보고얘기해요!
수고많으셨습니다~

**Comment by hyejungg** [comment]
## 결론
현 브랜치에 있는 langchain 코드를 가져가고 새로 만들어버리자 

## 회의 내용 
- 현재 레포(public 레포)에서 진행
- PR 올라와있는거까지 Merge 하고 1.0.1 뭐 태깅 하고, 코드 유지 X 새로 진행

1. html 반환하는 lambda (api)
- request 로 site url 을 넘겨주면 html 만 response 로 반환
      - content-type 을 넘겨서 html 을 response 하거나
      - optional 한 option 을 같이 전달해서 selector 전달하면 그쪽에 대한 html 태그만 response  

2. 뉴스봇 에이전트 lambda 
- 시작 노드 : db 접근해서 site 정보에 대한 배열 반환
- 병렬로 노드 수행
   - function calling 으로 html 크롤러 수행 (1번 lambda 호출)
   - response 로 받은 결과를 [{title, url}] 형식으로 가공 (llm 쓰던지 말던지)
   - llm 기반으로 AI, llm 관련 기사만 필터링
- 병렬로 노드 수행한 결과를 합친 노드 : db 접근해서 message log 가져와
   - 중복 메시지 제거
- 끝 노드 :  카카오워크 메시지 전송해

## 역할 분담
- [x] @hyejungg : 현재 코드 바탕으로 프로젝트 초기 세팅 + db 연결
   - news-agent 폴터 내에 프로젝트 초기 세팅하기
-----
- [x] @jongwoo328 : 1번 람다랑 태그 파싱 에이전트 노드까지 개발
- [x] @hyejungg  : llm 기반 필터링 노드 개발 
-----
- [ ] 중복 메시지 제거
- [ ] 카카오워크 메시지 전송
- [ ] 배포 수정 (git action, docker build)

## 우선 일정
- 11월 말에는 끝내자! 

## todo
- [ ] 병렬 실행에서 하나가 실패하면 어떻게 되는지 확인 필요 
- [ ] 중복 제거는 개선을 어떻게 하면 좋을지 생각해보기
