### ISSUE TITLE
html 반환하는 lambda 구현

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#49]

**Comment by hyejungg** [comment]
저희 Html parser lambda 를 수행하는 tool 실행 후 결과를 agent 가 사용하도록 하기로 했던 것 같은데 맞을까요??

그렇다면 tool 이 graph 가 가진 상태를 업데이트 하는 것이 불가능해 보입니다
https://github.com/langchain-ai/langgraph/discussions/1247

그래서 결론적으로는 tool이 아닌 html parser lambda agent 로 동작하게 하여야 할 것 같습니다. (현재 껍데기 노드가 존재하는데 그걸 살리는 (?)는 방향으로요..)

1. lambda api response 결과를 상태에 저장하는 agent 로 동작
2. 이후 response 값을 바탕으로 title, url의 키를 갖는 객체 형태로 변환하는 agent
3. 그 값들 중 gen ai, llm 등 키워드 기반으로 필터링 하는 agent

...

이런 식으로 동작 되어야 할 것 같아요.
제가 파악된 내용은 이러한데 저스틴이 작업하실 때 될 수도 있으니... 한 번 더 확인해 보셔도 좋을 것 같습니다!

----

E2e 더 자동화하기에서 tool이 state 에 있는 값을 사용하고, 결과를 state 에 저장하여 최종 노드가 state 에 있는 값들을 바탕으로 e2e 테스트 코드 작성을 시키려고 하던 도중 잘 안되어서 관련 논의를 확인했습니다... 😭

**Comment by jongwoo328** [comment]
확인 감사합니다 
state 변경코드 없이 agent가 tool을 이용해서 스스로 값을 변경할 수 없다는 말로 이해했습니다~
node 추가하는식으로 해야겠네요
