### ISSUE TITLE
배포 자동화 로직 수정

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#53]

**Comment by jongwoo328** [comment]
가능하면 .env를 도커 이미지 빌드에 포함하지 않고 sam의 --parameter-overrides 옵션등으로 람다 환경에 바로 넣어주는 것이 더 용이할 수 있음 나중에 할 때 참고하기

sam deploy --prarameter-overrides phase={}

**Comment by jongwoo328** [comment]
이미지 방식에서는 env가 고정되기때문에 힘듬..
aws parameter store를 쓰고
parameter override는 phase 만 해주고 
코드상에서 parameter store의 phase별 변수를 받아오는 방식??

**Comment by jongwoo328** [comment]
아니 sam build에서 parameter override 가능함!
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html

**Comment by jongwoo328** [comment]
아님 근데 이건 template에 값을 주입하는 용도라서 metadata의 DockerBuildArgs를 같이써야함

**Comment by jongwoo328** [comment]
template에 buildArgs를 선언한다
-> .env를 제거한다
-> sam build에 parameter override를 추가한다 (github actions 에서)
...
?1) 로컬에서는 어떻게 할 것인가?
?2) 이러면 phase별 이미지를 관리해야 한다...

**Comment by jongwoo328** [comment]
최종방식) .env를 다 빼버리고, sam deploy의 parameter override로만 다 전달하면 된다! 
로컬에서는  local invoke를 쓰거나, .env를 그냥 사용하면됨

**Comment by jongwoo328** [comment]
@hyejungg 
쉬는날 죄송합니다~ 시간될 때 한번 보시고 생각해주세요

외부에 공개되면 안되는 환경변수는 aws parameter store를 사용하는게 어떨까요?
우선 비용부분은 고급 파라미터가 아니면 공짜라서 괜찮을 것 같습니다

phase별 배포를 하려다 보니 
일단은 이미지를 phase별로 빌드하지 않으려고 생각을 했구요. (환경변수만 다른데 이미지를 중복 저장해야 하는 문제..) 
결국 동일 이미지에서 sam 명령어로 환경변수를 넣어줄 수는 있긴 합니다 (parameter override) 
그런데 그렇게 하면서 설정내용도 저희가 공유를 하려면 samconfig.toml에 내용을 선언해야하는데 public repo다 보니 이걸 코드상으로 관리하면 안될 것 같아서요..

그게 아니면 parameter override로 환경변수만큼 옵션을 줄줄이 적어줘야하는 불편함이 있습니다
물론 samconfig.toml을 gitignore 처리하고 거기 넣고 쓰는방법도 있긴 하지만 값이 바뀌면 지금 .env 관리처럼 매번 별도로 주고받아야하기 때문에 aws parameter store 사용하는게 좀 깔끔하지 않을까 해서요~

만약 그렇게 된다면
template.yaml과 sam 명령어로는 phase만 넣어주거나 추가로 공개되어도 되는 정보를 넣어줄 수 있고, 나머지 정보들은 phase별로 parameter store에서 코드상에서 가져오도록 하는게 어떨까 싶네요 

+) 코드상에서 가져오지 않더도 sam에서 넣어줄 때 참조할 수 있습니다
```bash
# 예시
sam deploy --parameter-overrides env1=$(aws ssm get-parameters --name /parameter/path  --query Parameters[0].Value)
```

**Comment by hyejungg** [comment]
> phase별 배포를 하려다 보니
일단은 이미지를 phase별로 빌드하지 않으려고 생각을 했구요. (환경변수만 다른데 이미지를 중복 저장해야 하는 문제..)

phase별 이미지 빌드는 필요해보입니다. 
현재 코드 상태에서 phase별로 .env 파일이 변경되진 않지만 prod/dev/local 환경에서의 코드는 다르므로 이미지를 다르게 저장해야 하는 건 필요해보이는데.. 혹시 제가 잘못 이해하고 있는 걸까요?!

> .env 관리처럼 매번 별도로 주고받아야하기 때문에 aws parameter store 사용하는게 좀 깔끔하지 않을까 해서요~

좋은 것 같습니다. 그런데 개인적으로는 template.yaml에서 동적으로 생성하고 관리까지 할 수 있다면 더 좋을 것 같아요 ... 
parameter store를 콘솔에서 생성해주고 사용해야 한다면 phase별로 누락하는 경우도 존재할 수도 있어서 현재 template.yaml로 관련 리소스를 모두 관리하고 있으니까 같이 관리하면 좋을 것 같아요.

+ [이런 글](https://www.linkedin.com/pulse/aws-samserverless-application-model%EA%B3%BC-parameter-store%EB%A5%BC-%EC%9A%B0%ED%98%81-%EC%A0%95-bkwlc/)도 있어 참고하시면 좋을 것 같습니다.


관련 정보 찾아봐주셔서 감사합니다! 🙇‍♀️

**Comment by jongwoo328** [comment]
처음 글의 의도는 지금 PROFILE에 따라 분기를 해 주니까 코드자체가 phase에 따라 다르지는 않고, 지금 상태를 유지한다면 phase별 이미지 빌드가 필요한 것 같다고 생각했어요. 그런데 저는 PROFILE 값만 바꿔주면 되는 상황에 저희가 쓰는 PROFILE 개수만큼 이미지를 만들어야한다는게 비효율적이라 .env파일이 아니라 환경변수를 넣어주는 방식을 바꾸자는 말이었어요

두번째 말하신 내용에서 template.yaml에서 관리하게되면 그걸 사용하는 의미가 없어집니다. 넣을 값을 숨기려고 쓰는데 template에 값을 명시해야하는 상황이 와서요.. 그래서 만약쓴다면 생성은 별도로 하고 template에서 참조하는 식으로 해야할 것 같네요

저도 계속 이것저것 보다보니 약간 헷갈리네요 보내주신 링크는 참고해서 다시 한번 정리해봐야할 것 같아요
감사합니다

+) 파라미터 스토어 없이 더 간단하게 가능할 것도 같아요!
