### ISSUE TITLE
news-agent 파이썬 코드도 람다에서 돌아가도록 수정

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#58]
- [x] template.yaml 추가

----

공식 문서 참고하여 작성해보기

----
참고 (관련 PR)
- #57 
- #46

**Comment by hyejungg** [comment]
@jongwoo328 
늦은 밤에 죄송합니다 .. 

그 news-scraper-agent 에서 scraper-lambda 를 호출하려면 이 [링크](https://stackoverflow.com/questions/60843259/how-can-i-invoke-another-lambda-function-also-defined-in-aws-sam-template)와 같이 같은 template.yaml 에 존재해야 할 것 같습니다. 

그래서 최상위 루트에 template.yaml 추가하려고 각 모듈에 존재하는 template.yaml 을 하나의 파일로 합치려고 하는데 괜찮을까요??

**Comment by jongwoo328** [comment]
오 거기까지는 생각을 못했었네요.. 생각해보니 그래야 되겠네요!
부탁드립니다~~

**Comment by jongwoo328** [comment]
해도 잘 안되면 일단은 IAM에서 * 적절히 사용해서 권한추가하는 식으로 해놓고 천천히 봐도 될것 같네요

**Comment by jongwoo328** [comment]
@hyejungg 알림 받으셨죠?

**Comment by hyejungg** [comment]
@jongwoo328 
알람 받으셨죠? 이거만 왔네요!

그러면 그렇게 작업하겠습니다~!~ 확인 감사합니다!
금방 끝날 것 같은데 시간이 늦어서 내일 작업할게요!!

**Comment by jongwoo328** [comment]
멘션이 없어서 그랬나보네요

**Comment by hyejungg** [comment]
참고한 문서

**sam 관련**
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/using-sam-cli-deploy.html

**template.yaml 내에 스케줄링 관련**
https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/using-eventbridge-scheduler.html
https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/sam-property-function-schedulev2.html
