### ISSUE TITLE
ecr 레포의 이미지 오래된 건 삭제하도록 웹 콘솔에서 수정

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#75]

**Comment by hyejungg** [comment]
sam template에 정의해두면 좋을 듯

**Comment by jongwoo328** [comment]
ecr 수명주기 규칙을 사용하면 최근 N개의 이미지만 유지하는 설정이 가능하네요. 
그런데 템플릿으로 적용하려면 ECR도 template에 리소스로 정의해야하네요
그래서 콘솔에서 적용했습니다
