### ISSUE TITLE
cloudwatch 에서 로그 표시 수정 

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#84]
local phase에서만 테이블로, 나머지는 그냥 출력

cloudwatch에서 표시하려면
항목당 한줄에 출력하고
탭이나 공백을 적절히 이용해서 구조화하면 좋을 것 같네요 (될지 모르겠지만요)

**Comment by hyejungg** [comment]
@jongwoo328 
지금 살짝쿵 코드 보면서 수정 중인데 질문이 있어가지구 언급해서 여쭤봅니다. 

1. logger 와 Console 은 다른거죠 ?! 
2. console에 표시되는 것도 logger 처럼 별도의 클래스로 생성해서 뭔가 쓰도록 하면 어떨까요 ?? 
3. 흠 .. 뭔가 phase별로 표시를 해줘야 하다보니 ... 이게 공통화가 어려울 것 같은데 if문으로 분기 태우는 것은 어떻게 생각하시나요 ? 더 좋은 방법이 있다면 제시해주셔도 좋습니다 👍 
```python
if env.PROFILE == "local":
  state.print_state(crawling_result=True)
else:
  self.logger.info(f"{여기에서 그냥 state.crawling_result를 json 포맷으로 출력 (intent 줘서)}")
```

**Comment by jongwoo328** [comment]
@hyejungg 
넵 logger는 파이썬 기본모듈인 logging에 있는 기능으로 만든 객체구요 (config/log.py 참고)

Console 객체는 터미널 출력 관련된 외부 모듈 (rich)에 있는 클래스로 만든 객체입니다

2번은 하나의 Console 객체를 같이 쓰자는 말인가요? 좋네요 제가 로그 구현할때는 기능마다 생성했거든요

3번에 써주신것 처럼 일단 if로 분기해서 하는거로 시작해보시고 너무 중복이 많아서 기능추가할 때 복잡해진다 싶으면 그때 공통화를 고민해보시죠 

만약 그렇게된다면 
- logging용 클래스 생성 (logging, rich.console 기능을 모두 포함하는)
- 그냥 rich를 버리고 logging 모듈로만 로깅 (출력형식을 조절해야겠지만..)
지금은 이정도로 생각나네요

**Comment by hyejungg** [comment]
[richHandler 시간 표시 타임존 변경 github link](https://github.com/Textualize/rich/pull/3574)
